import { Router } from "express";
import auth from "../../Middlewares/auth";
import * as userController from "./user.controller";
import * as userSignIn from "./user.signin";
import * as userUpdate from "./user.updateName";
import * as userSignOut from "./user.signout";
import * as deleteUser from "./user.delete";
import * as updatePassword from "./user.updatePassword";
import * as userProfile from "./user.profile";
import * as myProfile from "./user.myProfile";
const routes = new Router();
routes.post("/signup", userController.signUp);
routes.post("/signin", userSignIn.signIn);
routes.put("/updateName", auth, userUpdate.update);
routes.get("/signout", auth, userSignOut.singout);
routes.delete("/delete", auth, deleteUser.deleteUser);
routes.put("/updatePassword", auth, updatePassword.update);
routes.get("/userProfile/:userId", auth, userProfile.userProfile);
routes.get("/me", auth, myProfile.myProfile);

export default routes;
